travis:
  secure:
    BINSTAR_TOKEN: ihPnVwpro+Iwj6nntpx+ETiW0x8wSkVFlIObQhL7741+seGHh4su/n2K1JsnU+5da06e+fERiWB7Tni1AOOMCWD231EhXIj0hgYciGxcHkS/cBskyPs4mWRuTBxLB31WxWLZOMO4ueZ0bX49cdvgLohz6AQbKNYGqUHc2+u9Fw11/obpY/eW8x9m10dnXEMItyHM1z9gMfOdZ1rXFE+IvLVBpOrbPXUVYIIBgSnk6OHnSZO+3yfGg2Bjh1zYEzCCNvxoB5V856E1hDQ+FimOVCvpug5ZAAcI55BpjSpSegOI+y14lX8wSNlf2Y2TbvG7Rjb8QllKiPIOL8gggXStohD+1TWgxudlYkg8K2AYgB25AdXla9W03imjm7eP4rn+FlALzF9so3FvFL5C1yWYc2V6Xn+NS8fMRe3XlJmajOQI+NkPNZSYqQlsijsnI4HH75+yLSkiTeSljrnprIxTC2gpmnJ7NIthTsheRLua2s+1hQOero7bNOJ65hiTmOrfLE+/2zChmIIpEZhLACQO2OknAhqNKMQdRRegedQn5mn/FzJZe2Fognfq5Kof84uAJKJW1njxjxPs1WPH1J5dGWY+6I6/XIdEBVtfHem7D0SIbfsaVpEI1TFybn747xn/0cr8s6aglO1DF9H0iP8py4wcjQfYvFejrSLbilUjZQc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
