travis:
  secure:
    BINSTAR_TOKEN: vECPXTtZBHw6AFJdz6i1nqj6RbKABmZjkPIR0X55c6PMs2a+b1xgV5PDubiq8HKBdL66g7FPi1JFDvdXhbjoqQaigEYdElJtAKENx6invhTpfPMhIOqjp0aXUnb/LtuLKRZDVZsIr8lnikw4BrhQBlYaqHwv7tUAUe3btO+E/oqPdThyi3J0VTOx3UHhtVdkro4r/ie61+ClfS52jZBOUmGv0r6dHGEAqK6eJd84moO/HKwLhU5HMHbUQFXrXPlVkQUce2nRSjXaeJ6F6PJTzhvPUox3FvYDg/JFOG1bpw9YpGUrY2/O/smkNy+D12NqYj9PQmurXzbXSn1sgvd/SNeCeDc4gdBBnjsenCFUMa0/x0O3B2zBUeiktYAH7GJKhQ/JqQzQVhNVsEhHs97WdwJCl14H8uG+RJG8ZzCdM0I/GxI3Iz6S5A1NfZ3CWPeWAoKR9+pvpOCM2d7pcd9EPSgEaacmEDhnGScrhrAqO3mEZcLxQz/q1O+r2UHiZPp01ea0jOYt7+b7G5MKJtuShKtr/CsnvKPyGV/OrI10FmcOTFVUvszEu36XdKWbDjqOXB+sXrh1RuX/tHlbTmRkOyFuhJpOay1V/cocFI/HtHTqEBCcZChEbQ3oR4anhWWMRQMr6D54LWV4dfLOZ07nwv6N6KD60CRR5HNYCJhl72A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
