appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fRl2+HbdYeERm4wuM/ijJQ1/xchq+vfYpe7ugls8mm1rnFW0DrMjUU4z3/LmUoeZIcjRx15C3Ioda/xZEzzUzt6slkkcjdEmmIH3Ft59CeOB6pK+z5WdXgvgAFAllsMH+8Zkzk6WHP2cxqG/Jr+PM39jtgDdLda2kVBq3PkrR/IuIxloDezANqsi3CGA0RyGDCTIQmeUrjX2Mu58vNkRq6gLayy/ZPyUyawAzdwSczNYyNF3iwIxL1oAzrb8+qaU30MaikeeEbYKtk9Fki5R795wqrUUP/FZJO/6n9gCSjVZipZeM/fuCyqfY2MmUWPtUli2aM3PZCjB2jO8uYb0SRaDiLIsjtI08AIePcjCOTlX4llik0RWdh+fr9AEaAXd6XA+8N8eWfsBYrx6jvJLQYnJWzOGSrGtpaR5Jt1tKHjLdxl/5eGfg5h9ORSIuPAxXch4e1af4/WoyVe4C3duJIDo4cPlSFy7C05Mr+5PZvQywrV9FD0OxLbz84ziUDmyjivbalzfLZY/jAW2hGZAKYT63D2F6us7zWDgxH3kJa9ulyjdGPXxk2pt+EoF7QAp6y8OkzlUb/qaUorHOclSsagbQlzT7m3NOoArCKKpUXmTsm5iwbjVRdjkE3IO7s6UTK/vnfYJ9HchBU2Nc42F9JOVTUJQR9uGe06b73HussA=
