travis:
  secure:
    BINSTAR_TOKEN: qj87GMutY/k6BmtbgOjfZwIJ56aiADosf7qWasq38cJG57DIUDrWz+WVHewACeOz9wlvByF+Adqt5ev98IacQkVxHWeERb8EhUnBlL3fxVfM2lDKFqse1WNziGeWmGjuu67E1KS2n8DZmpLYlsl2s7HnMRLohSamBy7J7v4avW77fqTYWb4cMiyLItutFDZRcbdaQOGZTq5EYJAzOtV9GDLhDiwvfpxc4WcTY4flFZF4ivq7duicc+hRuksnewePyL1sa99T2iv+uti61uRAyCqsyIGaqinnYxLkCINCwwRfY+dBUnZE5201jrrjsYDHiG7EnTrx/QzTYKDtI7AqFVBGOtlJhPPt6znW7y48QtibS+PFXAqnYDTzjsRsLg1Mtfg7tkjOEaHs/dbrdhLJlxwNSaesDGC1cA3SudD4e7G4aISV3jDc0XKaqculnrCB9OwlA+XF6Wyp0ZYTWYWhcFYYyvC3me8woVYYlz326AXD+7QYfuYrjdF0Qjunn+taTfFgCGyqYrKWsB+5VNwOm71wIfmwjpGwr13HxyqKjM9zpsCBy+RBRkhYfDObcZk2nfHqerRqmJ7laqtZRF6feTD/yQ0AsyDz2/rXF6s2kIg6OWVbwDx2AsdcDlX/4b85XyZysYAQ8hKATm9PAZ3f3971ttgVXFSod7Ey1uMwpPk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
