travis:
  secure:
    BINSTAR_TOKEN: u/cTP7uQmj35H8fSS1qLwQiENNI5JintLwECzHlFq/g0D68aqftwYmtyxppqyh7rPfvyrcxHUjfPhtUbBc/fB+mXdWLooJggU6AexeICEUNn2x9iXmzrIIsIf9f4xmCKV6nCsH6yWP92DIhstVSVRC3UflooONya2i5zw3S1xRDoYT+Fmx0yoAfxkjAtSYtiMmtNdr2ju2xktJJkWhDMaixCP1WgCgzAe/v3DvaYxc06IxHUpS6OJLYpv9LHM/zE3PqfB88CSGTN7072B0tT5PsAWfHwjbeF2jhBVR+UjmwXXGWOWBhWHP4gPzKrVlYCQTTDG4Yh98sBiz00o0AIfKLjB5SqAmPCNqyk1oTb+xOCMMn7R4UVo7wVaxIz36dWQwMpGV4g4OjVrWTGPnkdgHg3oG27zI2M2CRP6td5qKZcDLa61Amjvrxu5eqsdrYDTwaZPpw17IbnigMRd0HP5fhDjW4l52YfrKu/0WET/uoxiXTgeI6qiKxD+nzD/2N30b6dxmFmn7IXUV95gBHp+JyQQ2bPBSd4RgLD4fHTxLBsWCHqi0pGOT4J2HjmEoHKw+hW+iMVPbfR08vuORg9sO1Y81THvw8ATfmuhuzm193nulMY197SLf7cUTvRnacC2H7onqC1dpcepQIF/IVJBNpVyXXDyvuScZuWG5nLNiE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
