travis:
  secure:
    BINSTAR_TOKEN: GhyYS5bY9GaK9kG8GtKDNeHnqV27EIHMTRqi5yMgBD9UAQkK8JPVA+DzTG5wMym8zI9HhOK3HgGuzV2BBVlGi0FjZjDa+rMSEORFGLfY2r+7XZ5282qzdvoWkYc1c0OeGXQtHPi/mV2LBxuIzwMdQxOhzNTArVhArvgTwzrOb8qqmPvYFeu3F2XlgtZofWlPJi/DOH0XlfhSTIxDGd63V/FlyWCskIVMwWw9iq00j+uYk5l3pyTuXokRijk/9MJsDYNPkQ9z7envp/nITrMGobos+sFz/dWNZqGZ1IsnqTYkgev3NM6bNu7Migja49xUyS5Z7wfodyKmuTblLjYfTNITTfAcGX6GwZcDCw/rmz9B+Hw5qbqRVp3q42lVHTcY8tQ0icnEL9xCmXEXCeQWCxjaheH7YhkaO1DuBqQoONBtkWfighxOUtQ8JQSlcNdyKM8TGxWzeE5EVMGtfn17Jh15hMsHktNdWuUeZ1kqE9ZJPjuN7T4oMz6NblC6WmSUmY2FAu9LQTzCbYR3lPtPuWLG8ZWKdfEBzDVaTaz1O2JxejdyrPm3iNUzYwQ4H8DUKYa+ZwrtmIY8vvJrn1YQ3v5bFFNSLCoxa+sT7fIfZQYgNSTmyeZ/b26EhASLYmafazkS33f2Q5Cfu7V9VMJ10c/vHDk/wOIYi4lfrSOphSk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
